version: '3.9'

services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - mlbnet

  streamlit-ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - flask-api
    networks:
      - mlbnet

networks:
  mlbnet:
    driver: bridge
