FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl gnupg2 unixodbc-dev gcc g++ libgssapi-krb5-2

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["streamlit", "run", "mlb_streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
